### ISSUE TITLE
Make variationanalysis-apps Public on DNAnexus

### ISSUE THREAD

**Issue by Damien-Black** [CampagneLaboratory/variationanalysis-apps#2]
Turning PR #1 into an issue.

I noticed there's a lot of documentation written for the variationanalysis tools, also [a great tutorial](https://github.com/CampagneLaboratory/variationanalysis/blob/master/SOMATIC-TUTORIAL.md). The primary issue from the prior code review, over email, was providing users some guidance to use the applications.

I recommend linking back to some of the documentation already written on the [variationalanalysis](https://github.com/CampagneLaboratory/variationanalysis) GitHub. Additionally, you can add recommendations and warnings. I believe warning against using `latest` as the docker image version was discussed in the code review.

I've added a checklist to this PR so we can tackle the primary issues and get the initial versions of these high quality apps published:

- [x] Add `details` field to _dxapp.json_. [description of _details_ field](https://wiki.dnanexus.com/App-Metadata-Conventions)
- [x] In `details` field specify `whatsNew`.
- [x] In `details` field specify `upstreamUrl`.
- [x] In `details` field specify `upstreamLicenses`.
- [x] In `details` field specify `citation`.
- [x] Add `Readme.md`
- [x] (Optional) Set `"openSource": true` in _dxapp.json_
- [x] (Optional) Add Readme.developer.md or remove uninformative Readme.
- [x] Publish apps
- [x] Remove  `"authorizedUsers": [...]` from the dxapp.json
- [x] Publish the app and add `user-sosazuwa` as a developer
- [x] Set  `"authorizedUsers": ["PUBLIC"]` via API call (DNAnexus Scientist will do this)

**Useful wiki links**

[Details field](https://wiki.dnanexus.com/App-Metadata-Conventions)
[dxapp.json spec](https://wiki.dnanexus.com/dxapp.json)

**Reason for removing authorizedUsers from dxapp.json**

`authorizedUsers` is actually not tied to the App version when you `dx build --app`. When it is specified in the `dxapp.json` we **overwrite** the current authorized users list and use the one in the `dxapp.json`, there's a warning prompt if there is a difference in users.

Internally our best practice is to add fields not tied to App version via [API call](https://wiki.dnanexus.com/API-Specification-v1.0.0/Apps#API-method:-/app-xxxx%5B/yyyy%5D/addAuthorizedUsers). From the CLI using `dx-toolkit` this looks like:

```
~$ dx api app-xxxx addAuthorizedUsers '"authorizedUsers": ["PUBLIC"]'
```

In fact this is the command I'll use to make these apps Public when this issue is resolved.

**Comment by manuelesimi** [comment]
Updated checklist:

  - [x] Add details field to dxapp.json. description of details field
  - [x] In details field specify whatsNew.
  - [x] In details field specify upstreamUrl.
  - [x] In details field specify upstreamLicenses.
  - [x] In details field specify citation.
  - [] Add Readme.md
  - [] (Optional) Set "openSource": true in dxapp.json
  - [] (Optional) Add Readme.developer.md
  - [] Publish apps
  - [] Remove "authorizedUsers": [...] from the dxapp.json
  - [] Publish the app and add user-sosazuwa as a developer
  - [] Set "authorizedUsers": ["PUBLIC"] via API call (DNAnexus Scientist will do this)

**Comment by manuelesimi** [comment]
Updated checklist:

  - [x] Add details field to dxapp.json. description of details field
  - [x] In details field specify whatsNew.
  - [x] In details field specify upstreamUrl.
  - [x] In details field specify upstreamLicenses.
  - [x] In details field specify citation.
 - [x] Add Readme.md
 - [ ]  (Optional) Set "openSource": true in dxapp.json
 - [ ]  (Optional) Add Readme.developer.md
 - [ ]  Publish apps
 - [ ]  Remove "authorizedUsers": [...] from the dxapp.json
 - [ ]  Publish the app and add user-sosazuwa as a developer
 - [ ]  Set "authorizedUsers": ["PUBLIC"] via API call (DNAnexus Scientist will do this)

**Comment by Damien-Black** [comment]
@manuelesimi 

In the `dxapp.json` you've added me as a developer, but in order to apply these changes you have to rebuild the apps.

can you execute the `build-all-apps.sh` command from your side. Then I will make them public.

Thanks again for the quick turnaround on these issues.

**Comment by manuelesimi** [comment]
@Damien-Black 

I know... it's the next step (and final) in the checklist above from my side :) 
I'm advancing the version for all the apps and then I'll republish them.

**Comment by Damien-Black** [comment]
@manuelesimi thanks! Let me know when they're ready for me.

**Comment by manuelesimi** [comment]
I rebuilt all our apps and they are available on the platform. I just want to make some test before make them public. It should take just few hours if there are no issues. I will update this issue when ready.

**Comment by manuelesimi** [comment]
@Damien-Black 

I'm done with the tests. Please, go ahead and make the apps public.

**Comment by Damien-Black** [comment]
@manuelesimi 
Quick question, do the following apps:
* genotype-pytorch-tensors
* prepare-sbi-unlabeled
* rtg-eval-vcf

Need CONTRIBUTE access to the project that launched them? If not, can you remove that from the `dxapp.json`

**Comment by manuelesimi** [comment]
Can you please remind me what CONTRIBUTE access means for the app? 

Looking at this description, I don't remember why we did set the access this way:

> Give the app(let) CONTRIBUTE access to the project in which it is run.  By default, an app will receive NO access, or if you build this as an applet, it will receive VIEW access.

**Comment by Damien-Black** [comment]
[CONTRIBUTE](https://wiki.dnanexus.com/API-Specification-v1.0.0/Project-Permissions-and-Sharing) access, means the App is allowed to make data changes in the parent project. Like adding, removing, and modifying `open` objects. Most of the time the App should have *no* special access to the parent projects

**Comment by manuelesimi** [comment]
@Damien-Black  Thanks for clarifying. 

That's probably an old setting that we do not need anymore. I removed it, advanced these 3 apps to version 1.0.1 and uploaded them again.

**Comment by Damien-Black** [comment]
@manuelesimi Great they look good!

You still need to run the `build-all-apps.sh` script. Only App creators can increment the version of the App.

Once the new versions are published I can make them PUBLIC. Let me know

**Comment by manuelesimi** [comment]
I did rebuild those I changed. They are available on the platform as unpublished with their updated version. Do I need to publish them?

**Comment by Damien-Black** [comment]
Ahh got you.

Yes you need to publish (set them as the default version) them.

**Comment by Damien-Black** [comment]
To follow-up, so it's clear

The API endpoint I'm referring to is [`app-xxxx/publish`](https://wiki.dnanexus.com/API-Specification-v1.0.0/Apps#API-method:-/app-xxxx[/yyyy]/publish)

From the Command Line Interface we use `dx build --app --publish {directory}`. In the `build-app.sh` script you've made that would just mean adding the `--publish` switch.

**Comment by manuelesimi** [comment]
I just published all the apps in their latest version.

**Comment by Damien-Black** [comment]
The Apps are now PUBLIC!

Thanks for the hard work @manuelesimi , you can close this issue and remove me as developer from the Apps in future revision. They should remain PUBLIC.

I think it would be very nice to bring Campagne Labs to the forefront when users see these apps in the [App library](https://platform.dnanexus.com/apps). I recommend prepending "Campagne Labs:" to the `title` field in the `dxapp.json` so in the UI users see "Campagne Labs: DL Genotype Caller" for example

**Comment by manuelesimi** [comment]
Terrific! Thanks @Damien-Black 

Just one last question: now that they are PUBLIC, if I rebuild and publish a new version, does it become automatically PUBLIC as well?

**Comment by Damien-Black** [comment]
Yes it will be public. the idea of` PUBLIC` is tied to the App itself, not the versions.

In the future, the app, as you update it, will still be public. Just **don't add** the `authorizedUsers` field to the `dxapp.json` or it will remove my `PUBLIC` change.

Feel free to email support@dnanexus.com if you encounter any issues.

Thanks again for getting the changes done so quickly!

**Comment by manuelesimi** [comment]
Got it!

Thanks a lot for your support along the process.
